### ISSUE TITLE
Enable eslint, select the right standard for typescript and update code

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-sdk-typescript-javascript#407]
At the moment, the typescript SDK partially uses tslint for code style checks. 

Current problems:

1. It's only executed on demand by a dev, not running against all the folders.
2. The generated code may break the rules
3. It uses old rules a newer tslint doesn't understand.
4. tslint is being replaced by eslint.
5. Rules are not enforced by Travis

In this task we should:

1. Remove tslint and tslint rules
2. Add eslint support to npm package.json
3. Select the right set of rules to be used that work for typescript. Base the rules on the community standard (maybe https://github.com/airbnb/javascript?).
4. Fix the code as necessary.
5. Integrate with Travis and force the rules
6. If possible, the dev's IDEs to eslint and enforce the rules before is even committed. 

Note that generated code like catbuffer and open API clients are being externalized into their own generated versioned lib that could be used independently.

**Comment by rg911** [comment]
As discussed, tslint is gradually merged into eslint at some point in the near future. We should definitely look for migrating to eslint.
