### ISSUE TITLE
Cosignature bug

### ISSUE THREAD

**Issue by decentraliser** [nemtech/symbol-sdk-typescript-javascript#417]
**1. Expected behavior and actual behavior.**
Should be able to cosign all transactions with A in the following setup (without using C's private key)
But the SDK only cosigns A's and not its child

**2. Steps to reproduce the problem.**

1. create account A normal
2. create account B normal
3. create account C multisig with 2of2 A, B
4. create account D multisig with 2of2 A, (C=>A,B) 

Try to cosign transaction 4 with A

**Comment by rg911** [comment]
@decentraliser what error did you get when announcing the transaction. Did you get the error from the server or from the SDK?

**Comment by decentraliser** [comment]
@rg911 so I tried the steps as described in the issue one more time,

there is no error thrown, it's just that signing transaction 4 with A will add a cosignature for A, but not on behalf of C

**Comment by rg911** [comment]
> @rg911 so I tried the steps as described in the issue one more time,
> 
> there is no error thrown, it's just that signing transaction 4 with A will add a cosignature for A, but not on behalf of C

Looks like expected to me. If C requires 2 cosignatures (A & B), to make TX4 complete, both A and B are needed for cosigning.

**Comment by decentraliser** [comment]
OK! this issue was suggested by @evias
I think that in some ways it makes sense that A can not sign both
transactions
In the wallet the behaviour is OK with that, A can sign for A, and B can
sign for C

Le lun. 20 janv. 2020 à 15:07, Steven Liu <notifications@github.com> a
écrit :
