### ISSUE TITLE
Method to query transactions from namespaceId

### ISSUE THREAD

**Issue by decentraliser** [nemtech/symbol-sdk-typescript-javascript#424]
Currently, we have no available methods to retrieve transactions that were sent using a namespace as a recipient, by querying the namespace.

However, it is technically possible to do so with REST (see below)

I propose to transpose `AccountHttp` transactions methods, as well as `Listener` transactions methods like so:
```
namespaceHttp.getTransactions(namespaceId: NamespaceId, queryParams?: QueryParams): Observable<Transaction[]>; {
...
return accountHttp.getAccountTransactions(namespaceIdAsAddress, queryParams)
}

```

> > i believe you can by using the namespaceId in base32 and padding with 0s in the current endpoint

http://api-20.us-west-1.nemtech.network:3000/account/TGCXONQXR4VCN3YAAAAAAAAAAAAAAAAAAAAAAAAA/transactions

_Originally posted by @Vektrat in https://github.com/nemtech/catapult-rest/issues/165#issuecomment-576561336_

**Comment by rg911** [comment]
So at the moment, Base32 encoded namespaceId can only be used in rest when there `recipient` used as NamespaceId, it will not return anything to query `account/../transactions` when the namespaceId is only alias of the signer's address. Which I can see this is a fully working solution here. It will probably wait for a full rest implementation first.

**Comment by decentraliser** [comment]
right on, makes sense!
Feel free to close the issue, I guess it is not relevant until this gets sorted server-side
