### ISSUE TITLE
namespace_max_depth should not be hardcoded

### ISSUE THREAD

**Issue by decentraliser** [nemtech/symbol-sdk-typescript-javascript#455]
Just came across the declaration of `namespace_max_depth` that blocks the creation of a `namespaceId` when it has too many parts.

the `maxNamespaceDepth `is configurable in network settings, it can be more than 3

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/40fa287fe079560a7b97ba3bbccecbe8f08e93ab/src/core/format/Utilities.ts#L97

**Comment by rg911** [comment]
At the moment, we cannot get these configurations per network. We are discussing it with catapult-rest to see if an endpoint can be provided. 

But yes the hardcoded name depth should be made configurable.

**Comment by decentraliser** [comment]
Maybe you can just remove this namespaceId validation step, and not have
the SDK validate the depth of a namespaceId

Le ven. 21 févr. 2020 à 22:32, Steven Liu <notifications@github.com> a
écrit :
