### ISSUE TITLE
MosaicNonce.createFromHex failing on first block MosaicDefinitionTransaction

### ISSUE THREAD

**Issue by decentraliser** [nemtech/symbol-sdk-typescript-javascript#474]
Not sure about what is the root cause, but this is throwing an error with the new network

When calling `blockHttp.getBlockTransactions(1)`,
the network currency `MosaicDefinitionTransaction`'s DTO has a nonce of 0 (see below)

Then it will be passed to `CreateStandaloneTransactionFromDTO`, that will ultimately pass this `0` by `Convert.hexToUint8`, and throw

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/fa035d8c7f7c73b5a7d6266072822e0a289cf4cb/src/model/mosaic/MosaicNonce.ts#L48

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/master/src/core/format/Convert.ts#L58-L60
```
    public static hexToUint8 = (input: string): Uint8Array => {
        if (0 !== input.length % 2) {
            throw Error(`hex string has unexpected size '${input.length}'`);
        }
```

node/block/1/transactions
![image](https://user-images.githubusercontent.com/36499647/75744472-4b93d300-5d4f-11ea-9fef-efc317512eda.png)

**Comment by rg911** [comment]
Good spotted.
The mosaic nonce field type changed from hex to uint32 in rest response payload. Will need to add padding to make it 4 bytes

**Comment by evias** [comment]
Issue still standing with non-zero nonce. REST seems to forward the nonce in numeric format whereas SDK expects hex.

**Comment by decentraliser** [comment]
Heads up guys, just noticed a similar thing with mosaic duration, when it is 0 (unlimited), it is not returned as UInt64:

![image](https://user-images.githubusercontent.com/36499647/75881323-c6491500-5e59-11ea-8437-acc40f019d0f.png)
![image](https://user-images.githubusercontent.com/36499647/75881328-ca753280-5e59-11ea-8e8a-af331c1e0fbd.png)

**Comment by rg911** [comment]
> Heads up guys, just noticed a similar thing with mosaic duration, when it is 0 (unlimited), it is not returned as UInt64:
> 
> ![image](https://user-images.githubusercontent.com/36499647/75881323-c6491500-5e59-11ea-8437-acc40f019d0f.png)
> ![image](https://user-images.githubusercontent.com/36499647/75881328-ca753280-5e59-11ea-8e8a-af331c1e0fbd.png)

this is not quite right. as mosaicDuration is defined as `string` which should return the numeric string

**Comment by decentraliser** [comment]
Well, one is UInt, one is numeric, in the same query result

**Comment by decentraliser** [comment]
@rg911 could you please fix the duration bug in the next release?

**Comment by rg911** [comment]
will create a new issue for duration
