### ISSUE TITLE
Signed lock hash is inconsistent with the transaction hash returned by REST when tx is confirmed

### ISSUE THREAD

**Issue by decentraliser** [nemtech/symbol-sdk-typescript-javascript#475]
1. Expected behavior and actual behavior.
When creating a signed lock transaction, it's hash should be the same as the one returned by rest after a successful announce

2. Steps to reproduce the problem.
Try to announce a multisig conversion

![image](https://user-images.githubusercontent.com/36499647/75750589-84d43f00-5d5f-11ea-9b6f-5cf9416de40b.png)

3. Specifications like the version of the project, operating system, or hardware.
on latest testnet,  symbol-sdk 0.17.2

**Comment by rg911** [comment]
Tried on the local bootstrap (private build) all seems working fine for me. @decentraliser which network are you using?

**Comment by evias** [comment]
this is using 0.9.4.1 ;  currently still internally managed: http://api-harvest-2-01.us-west-1.symboldev.network:3000/node/server

**Comment by rg911** [comment]
I have tried above example + SDK's e2e test:
- On local server (private build tag: 275877a503 + master catapult-rest) all okay
- On http://api-harvest-2-01.us-west-1.symboldev.network:3000/ I am having the same hash mismatch issue. 

Seems infrastructure issue to me?

**Comment by evias** [comment]
fixed with latest
