### ISSUE TITLE
LockFundsTransaction should be HashLockTransaction

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-sdk-typescript-javascript#478]
The name of the transaction [LockFundsTransaction](https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/master/src/model/transaction/LockFundsTransaction.ts) should be called `HashLockTransaction`

@dgarcia360 @rg911 should we rename it to keep the consistency? Doc says `LockFundsTransaction` is an alias

**Comment by rg911** [comment]
There's already an alias type created for HashLock in the sdk
