### ISSUE TITLE
Add calculatingMerkleRootFromBlockTransactions method to BlockService

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-sdk-typescript-javascript#481]
Add a `CalculatingMerkleRootFromBlockTransactions` method to the BlockService.

The reference implementation can be found in the comment

https://github.com/nemtech/symbol-docs/blob/517aaa9b9d95479c8705b87bb872bf401fd2ce8e/source/resources/examples/typescript/blockchain/CalculatingMerkleRootFromBlockTransactions.ts#L35

Please note that the reference implementation only takes the first 100 transactions. Our implementation should stream the pages and calculate the Merkle root as pages are processed without putting all the pages into memory.

Java issue:

https://github.com/nemtech/symbol-sdk-java/issues/243

**Comment by rg911** [comment]
Waiting for the pagination works done on rest
