### ISSUE TITLE
MosaicDuration in wrong format when the value is 0

### ISSUE THREAD

**Issue by rg911** [nemtech/symbol-sdk-typescript-javascript#485]
https://github.com/nemtech/symbol-sdk-typescript-javascript/issues/474#issuecomment-594502028

**Comment by rg911** [comment]
@decentraliser Which did you get this error? `createTransactionFromDTO()` or from other functions?

**Comment by decentraliser** [comment]
Hi,

Sorry, this looks good to me now! This issue can be closed
