### ISSUE TITLE
Return namespaces names from namespace and mosaic endpoint.

### ISSUE THREAD

**Issue by AnthonyLaw** [nemtech/symbol-sdk-typescript-javascript#499]
it's big overhead return namespaces names from the sdk?

`NamespaceHttp(http.nodeUrl).getNamespacesFromAccount`
`AccountHttp(http.nodeUrl).getAccountInfo`

because in client apps development, we need make extra call for the names endpoint to get namespace name

@evias @decentraliser 

related topic
https://nem2.slack.com/archives/CEZKUE4KB/p1583900407059200

**Comment by evias** [comment]
Which endpoint would you want to add names to?

**Comment by AnthonyLaw** [comment]
1. it return Array of Mosaics[], if it can involved namespace names will be good.
http://api-01.us-west-1.symboldev.network:3000/account/TCGJKJDR72EFJC3AOUMW27HSW2WQX5SASLIZUYAT

2. it return namespace object, all the infomation about the namespace, but without the names, it seem not helpful.
http://api-01.us-west-1.symboldev.network:3000/account/TDZC7KMLVKL2OV7CMGUV3LT66WXRM3J6V3QYIKPR/namespaces

http://api-01.us-west-1.symboldev.network:3000/namespace/D8EC2FD3E488B037

**Comment by rg911** [comment]
@Vektrat @dgarcia360 Is it easy to add the namespace name to the above endpoints?

**Comment by Vektrat** [comment]
this is related to https://github.com/nemtech/catapult-rest/issues/223, which is not to be seen as a task that is pending to be completed because this resolution would be heavy on server side, this has been discussed multiple times and the outcome has always been that clients need to resolve themselves as they need them

**Comment by rg911** [comment]
For accountNames, you can use `getAccountsNames` in NamespaceHttp 
@AnthonyLaw

**Comment by AnthonyLaw** [comment]
@rg911 yeah, i currently using it.

> resolution would be heavy on server side

good to know, thanks.
i will close this issue.
