### ISSUE TITLE
Refactor simple wallet key encryption to use standard AES

### ISSUE THREAD

**Issue by rg911** [nemtech/symbol-sdk-typescript-javascript#524]
To eliminate the security vulnerability (rainbow tables for sha3 ), it is proposed to:

- `toMobileKey` to be renamed to `encrypt_pbkdf2`
- `derivePassSha`, `passwordToPrivateKey` and `encodePrivateKey` to be removed
- instead use standard AES encryption / decryption with seed

**Comment by rg911** [comment]
Wait for NIP

**Comment by fboucquez** [comment]
Would this break exiting wallet data when used? @decentraliser

**Comment by decentraliser** [comment]
yes

main reason is that SimpleWallet was not using PBKBF2

**Comment by fboucquez** [comment]
What's the migration for current users?

**Comment by decentraliser** [comment]
What about the no-migration-path? :D

The migration path is: get your private key before the client upgrade, and
import it back in the upgraded client

I'm not sure that we should provide that in the SDK, that would make things
messy
