### ISSUE TITLE
Migrate "require" style imports

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-sdk-typescript-javascript#537]
Migrate require types of imports like `const CryptoJS = require('crypto-js');` to `import ... from ...` format

Once migration is done, there are some eslint ignore comments to be removed.

**Comment by decentraliser** [comment]
About CryptoJs, as discussed with @rg911 , the types provided in `@types/crypto-js` are broken

There are 3 solutions:

1.  Use require, stick with any, and do not use `@types/crypto-js` 
2.  Make a .d.ts file to override the broken types in `@types/crypto-js` 
3.  Fix `@types/crypto-js` 

As per disucssion with Rg, I went for solution 1 in #530

**Comment by rg911** [comment]
the typing class for crypto-js is not in a good shape as they have quite a lot issues right now.

**Comment by fboucquez** [comment]
Ok, fair enough. Is it possible to migrate the other require imports?
