### ISSUE TITLE
AggregateTransaction signedByAccount method

### ISSUE THREAD

**Issue by decentraliser** [nemtech/symbol-sdk-typescript-javascript#557]
https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/fbdbc0e0e0a20ac2faba1d5ce6d2867df34322cf/src/model/transaction/AggregateTransaction.ts#L274-L279

Here, the `signer` property is being tested. However, the `signer` property is optional, so when you call `signedByAccount` and `signer` is undefined, it throws:

`"TypeError: Cannot read property 'equals' of undefined"`

I think that it should be reviewed, at least a better error should be thrown

**Comment by rg911** [comment]
This method was internal before, I think it's your guys requested to make it public. The proper way to sign a transaction is by always using account.sign, unless it's interally used by the sdk

**Comment by decentraliser** [comment]
Closed the issue as I identified it wrongly, but I'm pretty sure there is a bug somewhere around it, will continue to investigate and reopen if necessary
