### ISSUE TITLE
Revisit how the TS SDK runs in a vanilla JS Browser

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-sdk-typescript-javascript#588]
It seems that the user needs to polyfill a client app when testing the SDK. This may be too convoluted and not friendly for quick development.
This story is to revisit how the SDK can run in a browser with just the JS compiled files and how the client can provide some of the dependencies (WebSocket for example) to avoid babel/polyfill 

The outcome of this story should be:
- Reduce the requirements needed to run the SDK
- Document those requirements and how to set up them if necessary.

**Comment by evias** [comment]
the fix **can be** trivial ; using a build:browser npm script we can just add webpack, which will bundle the sdk into a “commonjs” package named SymbolSDK that is then added onto window for browser compatibility. This process is also done in symbol-qr-library, using the npm script `build:browser` you will see it basically just runs `webpack` with a custom configuration.

there is another way to do this, with browserify …. but browserify is less "magic" … and comes with many “polyfill-x” and “polyfill-y” dependencies needs (e.g. `tls-browserify`, `net-browserify`, `level-fs-browser`, etc.)

webpack is just “npm install webpack” and then run webpack with correct configuration.

I will open a proposal PR in next hour to reflect a _proposal_ fix.
