### ISSUE TITLE
Remove replace in listener

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-sdk-typescript-javascript#590]
https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/060749f7c0b5cb7e8b1ac2242569e57fe3e2b60b/src/infrastructure/Listener.ts#L92

If the user provides a websocketURL, no `replace` is required. The URL should be used as is

This `replace` may be integrated to the generated URL in the factory when the user doesn't provide the url. 

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/master/src/infrastructure/RepositoryFactoryHttp.ts#L78

**Comment by rg911** [comment]
this is to make sure no `/` at the end of the URL string

**Comment by fboucquez** [comment]
Ok, not a bug. I thought it was replacing the /ws out of user-provided URL
