### ISSUE TITLE
Can't create account using SDK (Angular)

### ISSUE THREAD

**Issue by PavloTCentiva** [nemtech/symbol-sdk-typescript-javascript#624]
1. Expected behavior and actual behavior.
eb: paste code snippet into angular .ts file and get Account adress and private key.
ab: chain of errors

2. Steps to reproduce the problem.

- create new Angular project

- insert code snippet into app.component.ts file:
`import {Component, OnInit} from '@angular/core';`
`import {Account, NetworkType} from 'symbol-sdk';`
`@Component({`
 ` selector: 'app-root',`
 ` templateUrl: './app.component.html',`
  `styleUrls: ['./app.component.scss']`
`})`
`export class AppComponent implements OnInit{`
  `title = 'y';`
 ` ngOnInit(): void {`
   ` const account = Account.generateNewAccount(NetworkType.TEST_NET);`
 `   console.log('Your new account address is:', account.address.pretty(),`
      `'and its private key', account.privateKey);`
  `}`
`}` 

- try to start the project. (in terminal npm run start )

-there is an error:
 "ERROR in ./node_modules/futoin-hkdf/hkdf.js
Module not found: Error: Can't resolve 'crypto' in '/Users/sombramac-25/IdeaProjects/angular-nem/y/node_modules/futoin-hkdf'
ERROR in ./node_modules/symbol-sdk/dist/src/core/crypto/Crypto.js
Module not found: Error: Can't resolve 'crypto' in '/Users/sombramac-25/IdeaProjects/angular-nem/y/node_modules/symbol-sdk/dist/src/core/crypto'"

-this error can be fixed by adding next code into your package.json file (before "devDependencies"): 
` "browser": {
    "crypto": false
  }` 

-then when you refresh your browser page on localhost:4200 (angular default url) you can see error in your console :
"Uncaught ReferenceError: global is not defined"

-to fix this you can add next code to your polyfills.ts :
`(window as any).global = window;`

-and after this you get next error in the console : 
"ERROR TypeError: crypto.randomBytes is not a function
    at Function.push../node_modules/symbol-sdk/dist/src/core/crypto/Crypto.js.Crypto.randomBytes (Crypto.js:175)
    at Function.generateNewAccount (Account.js:61)
    at AppComponent.ngOnInit (app.component.ts:13)
    at callHook (core.js:2922)
    at callHooks (core.js:2892)
    at executeInitAndCheckHooks (core.js:2844)
    at refreshView (core.js:7213)
    at renderComponentOrTemplate (core.js:7312)
    at tickRootContext (core.js:8507)
    at detectChangesInRootView (core.js:8532)" 

Need help to solve this issue. Thanks!

3. Specifications like the version of the project, operating system, or hardware.
`  "dependencies": {
    "@angular/animations": "~10.0.2",
    "@angular/common": "~10.0.2",
    "@angular/compiler": "~10.0.2",
    "@angular/core": "~10.0.2",
    "@angular/forms": "~10.0.2",
    "@angular/platform-browser": "~10.0.2",
    "@angular/platform-browser-dynamic": "~10.0.2",
    "@angular/router": "~10.0.2",
    "rxjs": "~6.5.5",
    "symbol-sdk": "^0.20.6",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "browser": {
    "crypto": false
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.1",
    "@angular/cli": "~10.0.1",
    "@angular/compiler-cli": "~10.0.2",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0-next.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}`

Angular9
Typescript : 3.9.5
Symbol-sdk: 0.20.6
node: 12.18.0
MacOS Catalina version 10.15.5

**Comment by rg911** [comment]
This is related to #625

**Comment by fboucquez** [comment]
@PavloTCentiva , is this still an issue?

**Comment by Pavlo-Turchyn** [comment]
> @PavloTCentiva , is this still an issue?

It's working good now, thanks!
