### ISSUE TITLE
Add doc / wiki page for Angular 9.x compatibility patch

### ISSUE THREAD

**Issue by rg911** [nemtech/symbol-sdk-typescript-javascript#625]
https://github.com/44uk/ng2-with-symbol-sdk-sample/blob/master/patches/%40angular-devkit%2Bbuild-angular%2B0.901.11.patch

**Comment by fboucquez** [comment]
There is no compatibility issue since we move to fetch clients

**Comment by 44uk** [comment]
This is already updated.
Fixed link => https://github.com/44uk/ng2-with-symbol-sdk-sample/blob/90ed124487024a5a1c3e1631bc52aefb0b43b70d/patches/%40angular-devkit%2Bbuild-angular%2B0.901.11.patch
