### ISSUE TITLE
TransactionSearchCriteria can't use default of group

### ISSUE THREAD

**Issue by xembook** [nemtech/symbol-sdk-typescript-javascript#633]
I used TransactionSearchCriteria without specifying `group`.
because document says default of group is `confirmed`

https://nemtech.github.io/symbol-sdk-typescript-javascript/0.20.6/interfaces/_infrastructure_searchcriteria_transactionsearchcriteria_.transactionsearchcriteria.html#group

but, TransactionHttp.searchTransactionByGroup does not control the case where group is undefined.
Therefore, an error will occur.

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/e4056d319357a7e5222de385c4fb36c50dfbdf5e/src/infrastructure/TransactionHttp.ts#L219

Could you please check this? thanks.

**Comment by fboucquez** [comment]
Group was moved from query to path parameter in 9.6.3 and it's reflected in new TransactionSearchCriteria. You would need to provide a group. Example:

```
const criteria: TransactionSearchCriteria = {
           group: TransactionGroup.Confirmed,
    };
transactionRepository.search(criteria)...
```

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/master/src/infrastructure/searchCriteria/TransactionSearchCriteria.ts#L31

**Comment by xembook** [comment]
Thanks! I need to provide group.

**Comment by rg911** [comment]
We will update the doc.
