### ISSUE TITLE
Removing reserved fields from schemas (WS and API)

### ISSUE THREAD

**Issue by rg911** [nemtech/symbol-sdk-typescript-javascript#641]
Catbuffer does not return the reserved fields
Reserved fields are extra bytes(overhead) that are not used by the client. This can add up esp for aggregate transactions.
Reserve fields.
"aggregateTransactionHeader_Reserved1":0,
"embeddedTransactionHeader_Reserved1":0,
"entityBody_Reserved1":0,
"verifiableEntityHeader_Reserved1":0,

https://github.com/nemtech/catapult-rest/issues/375

**Comment by fboucquez** [comment]
Fixed in rest
