### ISSUE TITLE
listener.isOpen() returns always false

### ISSUE THREAD

**Issue by xembook** [nemtech/symbol-sdk-typescript-javascript#661]
https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/2b18ca2f991aa692dd4384e93b7377954faed695/src/infrastructure/Listener.ts#L200

I want to use listener.isOpen() on browser WebSocket, but  it returns always false.
because WebSocket.OPEN is always undefined.

I think it should be corrected as follows.
```
return this.webSocket.readyState === this.webSocket.OPEN;
```

please check this, thank you.

**Comment by xembook** [comment]
Please check if other places are behaving as expected.

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/2b18ca2f991aa692dd4384e93b7377954faed695/src/infrastructure/Listener.ts#L103

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/2b18ca2f991aa692dd4384e93b7377954faed695/src/infrastructure/Listener.ts#L210

**Comment by rg911** [comment]
@xembook good catch. it is a bug on injected ws listener. 👍
