### ISSUE TITLE
can we add get native namespace from SDK?

### ISSUE THREAD

**Issue by AnthonyLaw** [nemtech/symbol-sdk-typescript-javascript#693]
currently, SDK/REST is not able to retrieve Native namespace.

it can help get native namespace from different networks (private/mijin).

**Comment by fboucquez** [comment]
@AnthonyLaw 

In the latest alpha, you are able to get the `Currency` object from the repository https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/dev/src/infrastructure/RepositoryFactory.ts#L149.

That object contains the information for the network currency, you can create Mosaics from there

**Comment by AnthonyLaw** [comment]
Sound good, will take a look on that 👍
