### ISSUE TITLE
Invalid alias resolution in NamespaceHttp

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-sdk-typescript-javascript#699]
> Found something wrong in REST / SDK
> I can’t get Address alias from the namespaceID
> 
> Error message from SDK:
> Error: No address is linked to namespace 'E66AE40356B62BFC'
> 
> Debug in REST
> Transaction hash: http://api-01.ap-southeast-1.0.10.0.x.symboldev.network:3000/transactions/confirmed/DDFF6B57D45572A035EE5B0A6EEE7B2B9D2A12B671A7E0ED436037F2A15523E6
> 
> the recipientAddress: 99BDA029E259012FAB000000000000000000000000000000 is an unresolved id AB2F0159E229A0BD
> 
> http://api-01.ap-southeast-1.0.10.0.x.symboldev.network:3000/namespaces/AB2F0159E229A0BD
> and the namespace id show alias type: 0

Revisit mosaic id resolution too.

**Comment by rg911** [comment]
Not sure this is a bug..
The alias is linked to the parent namespace http://api-01.ap-southeast-1.0.10.0.x.symboldev.network:3000/namespaces/E66AE40356B62BFC

`AB2F0159E229A0BD` is the child level of `E66AE40356B62BFC`
