### ISSUE TITLE
PersistentDelegationRequestTransaction message is empty from SDK

### ISSUE THREAD

**Issue by AnthonyLaw** [nemtech/symbol-sdk-typescript-javascript#704]
![image](https://user-images.githubusercontent.com/5649156/98261790-cdfc2300-1fbf-11eb-9ff5-5d95445acc6b.png)

http://api-01.ap-southeast-1.0.10.0.x.symboldev.network:3000/transactions/confirmed/9661088F22C2DC72E76EE2B0F07BFC0D8E98EEE0CC8AE274362EDBB44F164F16

SDK Version: 0.21.0

**Comment by GodTanu** [comment]
The CLI is the same.  Below is the payload.

2401000000000000B69B5CB2CE79B5E06117D246E84CB21095BAC0E78A4F01E2  
D4E3F068EF2E3370B907495FE6BC9A130D05A8BDB49E8AD398FBA40569C92190  
7297AB0D5778C00D2D13E2FDC654936417899AB63D709B9A7A603BA1D20557AA  
06CE5B2C9242F035000000000198544140420F00000000009A19B31107000000  
981E13520236DBBD06F8C08710289BD9CF598A01C29E04668400000000000000  
E201735761802AFECBD67E2DBA5D69157CE32874EFDD680E41B1BFFD12B781F8  
4E8AD883920BBB50EA38AFE078E99EE5EE4BDFDA77E8C101EBD3100C0D471673  
471A61B23E513FC7E21F7803316B906A688F14AA75002913A3B57DD13469BC27  
CF8C82FD5C4C76867011AEDC7C4870D8C5AF9C175F0DA5A8E2AD3A327D868BFB  
A34A5E3D

**Comment by xembook** [comment]
I think last part of GodTanu's payload is 

//8-byte marker:
E201735761802AFE

//message body 
CBD67E2DBA5D69157CE32874EFDD680E41B1BFFD12B781F84E8AD883920BBB50EA38AFE078E99EE5EE4BDFDA77E8C101EBD3100C0D471673471A61B23E513FC7E21F7803316B906A688F14AA75002913A3B57DD13469BC27CF8C82FD5C4C76867011AEDC7C4870D8C5AF9C175F0DA5A8E2AD3A327D868BFBA34A5E3D 

I think MessageType of PersistentHarvestingDelegationMessage is `FE`.
what is `E201735761802AFE`?

**Comment by xembook** [comment]
and I try to this method,
```
nem.TransactionMapping.createFromPayload("2401000000000000B69B5CB2CE79B5E06117D246E84CB21095BAC0E78A4F01E2D4E3F068EF2E3370B907495FE6BC9A130D05A8BDB49E8AD398FBA40569C921907297AB0D5778C00D2D13E2FDC654936417899AB63D709B9A7A603BA1D20557AA06CE5B2C9242F035000000000198544140420F00000000009A19B31107000000981E13520236DBBD06F8C08710289BD9CF598A01C29E04668400000000000000E201735761802AFECBD67E2DBA5D69157CE32874EFDD680E41B1BFFD12B781F84E8AD883920BBB50EA38AFE078E99EE5EE4BDFDA77E8C101EBD3100C0D471673471A61B23E513FC7E21F7803316B906A688F14AA75002913A3B57DD13469BC27CF8C82FD5C4C76867011AEDC7C4870D8C5AF9C175F0DA5A8E2AD3A327D868BFBA34A5E3D")
```

then , error was shown
`Uncaught Error: Message Type is not valid`

**Comment by tomotomo9696** [comment]
After changing the endian of the first 8 bytes of the message payload, createFromPayload works and the delegate harvesting is successful.
 ```
persistentDelegationRequestTx.message.payload = persistentDelegationRequestTx.message.payload.replace(/^E201735761802AFE/i, "FE2A8061577301E2");
```

**Comment by fboucquez** [comment]
Fixed on alpha
