### ISSUE TITLE
Namespace aliases can have more than 1 in mosaic or account.

### ISSUE THREAD

**Issue by AnthonyLaw** [nemtech/symbol-sdk-typescript-javascript#730]
SDK : 0.21.1-alpha-202011262256

https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/1888cd00b1e7351a8784fdfdd868164406d321e0/src/service/CurrencyService.ts#L102

it should not filter for the first array.
It's because a mosaic can be linked to more than 1 namespace aliases.

**Comment by rg911** [comment]
This service is only for the Network Currency, so it doesn't really matter to select the top of the alias array
